version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "restaurant-auto"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-k3xvozsyatyy"
s3_prefix = "restaurant-auto"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

